### ISSUE TITLE
[FEATURE REQUEST] Use a real SQL based database

### ISSUE THREAD

**Issue by ghost** [Jimmy-Blue/Mercury#2]
If you use a real SQL database, everything is being faster, you can try to use SQLite3, there is a native Python module for it and its just a .db file.

**Comment by B1ue-Dev** [comment]
Which, I have not learned it yet.

**Comment by ghost** [comment]
Its very easy to learn, it uses English words like `GET` `PUT` `READ` and so on.

**Comment by ghost** [comment]
https://docs.python.org/3/library/sqlite3.html <-- Use this as a reference
